apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: gardener.kube-system.apiserver-proxy
  creationTimestamp: "2021-04-28T10:18:38Z"
  labels:
    run: example
  name: example
  namespace: default
  resourceVersion: "4733"
  selfLink: /api/v1/namespaces/default/pods/example
  uid: c84cc6e9-2f67-41d3-ab4f-c0203c94bf2a
spec:
  containers:
  - env:
    - name: KUBERNETES_SERVICE_HOST
      value: api.dttest.dynatest.internal.canary.k8s.ondemand.com
    image: nginx:1.13.5-alpine
    imagePullPolicy: IfNotPresent
    name: example
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-sj2bd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-sj2bd
    secret:
      defaultMode: 420
      secretName: default-token-sj2bd
status:
  phase: Pending
  qosClass: BestEffort
