{{- with .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .name }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}